In [4]:
import pandas as pd

In [54]:
df = pd.read_html('https://fbref.com/en/comps/Big5/misc/players/Big-5-European-Leagues-Stats',
                  attrs = {'id': 'stats_misc'})[0]

In [55]:
df

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk             Player             Nation
0                     1         Max Aarons            eng ENG
1                     2   Brenden Aaronson             us USA
2                     3    Paxten Aaronson             us USA
3                     4  Keyliane Abdallah             fr FRA
4                     5   Yunis Abdelhamid             ma MAR
...                 ...                ...                ...
2902               2792     Lovro Zvonarek             hr CRO
2903               2793    Martin Ødegaard             no NOR
2904               2794        Milan Đurić             ba BIH
2905               2795        Milan Đurić             ba BIH
2906               2796   Mateusz Łęgowski             pl POL

     Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                    Pos              Squad                Comp
0                    DF        Bournemouth  eng Premier League
1                 MF,FW       Union Berlin       de Bundesliga
2                    MF     Eint Frankfurt       de Bundesliga
3                    FW          Marseille          fr Ligue 1
4                    DF              Reims          fr Ligue 1
...                 ...                ...                 ...
2902                 MF      Bayern Munich       de Bundesliga
2903                 MF            Arsenal  eng Premier League
2904                 FW      Hellas Verona          it Serie A
2905                 FW              Monza          it Serie A
2906                 MF        Salernitana          it Serie A

     Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Performance  \
                    Age               Born                90s        CrdY
0                24-128               2000               13.0           1
1                23-202               2000               12.6           3
2                20-259               2003                1.1           0
3                18-036               2006                0.0           0
4                36-226               1987               28.9           5
...                 ...                ...                ...         ...
2902             19-003               2005                0.2           0
2903             25-146               1998               32.4           2
2904             33-355               1990               13.4           2
2905             33-355               1990               11.5           2
2906             21-103               2003               12.3           3

      ...                               Aerial Duels              \
      ... Int TklW PKwon PKcon OG Recov          Won Lost   Won%
0     ...   6   19     0     1  0    74            5   10   33.3
1     ...   2   17     0     0  0    81           12   16   42.9
2     ...   0    2     0     0  0     5            3    0  100.0
3     ...   0    0     0     0  0     0            0    1    0.0
4     ...  37   33     0     0  1   145           59   34   63.4
...   ...  ..  ...   ...   ... ..   ...          ...  ...    ...
2902  ...   0    0     0     0  0     0            0    1    0.0
2903  ...  13   16     1     0  0   151            3    7   30.0
2904  ...   1    0     0     0  0    25          135   43   75.8
2905  ...   0    5     0     0  0    25           67   36   65.0
2906  ...   7   11     0     0  0    60           13   16   44.8

     Unnamed: 25_level_0
                 Matches
0                Matches
1                Matches
2                Matches
3                Matches
4                Matches
...                  ...
2902             Matches
2903             Matches
2904             Matches
2905             Matches
2906             Matches

[2907 rows x 26 columns]

In [56]:
df.to_csv('mics_stats.csv', index = False)

In [57]:
df_1 = pd.read_csv('mics_stats.csv')

In [58]:
df_1.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,CrdY,...,Int,TklW,PKwon,PKcon,OG,Recov,Won,Lost,Won%,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,24-128,2000,13.0,1,...,6,19,0,1,0,74,5,10,33.3,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,23-202,2000,12.6,3,...,2,17,0,0,0,81,12,16,42.9,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,20-259,2003,1.1,0,...,0,2,0,0,0,5,3,0,100.0,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,18-036,2006,0.0,0,...,0,0,0,0,0,0,0,1,0.0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,36-226,1987,28.9,5,...,37,33,0,0,1,145,59,34,63.4,Matches

In [59]:
df_1.shape

(2907, 26)

In [60]:
df_filtered = df_1[df_1['Rk'] != 'Rk']

In [61]:
df_filtered.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,CrdY,...,Int,TklW,PKwon,PKcon,OG,Recov,Won,Lost,Won%,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,24-128,2000,13.0,1,...,6,19,0,1,0,74,5,10,33.3,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,23-202,2000,12.6,3,...,2,17,0,0,0,81,12,16,42.9,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,20-259,2003,1.1,0,...,0,2,0,0,0,5,3,0,100.0,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,18-036,2006,0.0,0,...,0,0,0,0,0,0,0,1,0.0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,36-226,1987,28.9,5,...,37,33,0,0,1,145,59,34,63.4,Matches

In [95]:
# df_filtered.to_csv('keeper_stats.csv')

In [5]:
ndf = pd.read_csv("defense_stats_.csv")

In [6]:
ndf

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Tkl,...,Tkl%,Lost,Blocks,Sh,Pass,Int,Tkl+Int,Clr,Err,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,24-128,2000.0,13.0,29.0,...,62.5,12.0,9.0,5.0,4.0,6,35.0,25.0,0.0,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,23-202,2000.0,12.6,29.0,...,50.0,15.0,25.0,0.0,25.0,2,31.0,4.0,0.0,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,20-259,2003.0,1.1,2.0,...,100.0,0.0,2.0,0.0,2.0,0,2.0,0.0,0.0,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,18-036,2006.0,0.0,0.0,...,NaN,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,36-226,1987.0,28.9,59.0,...,56.8,19.0,46.0,27.0,19.0,37,96.0,101.0,1.0,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2791,2792,Lovro Zvonarek,hr CRO,MF,Bayern Munich,de Bundesliga,19-003,2005.0,0.2,0.0,...,0.0,1.0,1.0,0.0,1.0,0,0.0,1.0,0.0,Matches
2792,2793,Martin Ødegaard,no NOR,MF,Arsenal,eng Premier League,25-146,1998.0,32.4,46.0,...,29.6,38.0,22.0,1.0,21.0,13,59.0,5.0,0.0,Matches
2793,2794,Milan Đurić,ba BIH,FW,Hellas Verona,it Serie A,33-355,1990.0,13.4,1.0,...,0.0,3.0,0.0,0.0,0.0,1,2.0,13.0,0.0,Matches
2794,2795,Milan Đurić,ba BIH,FW,Monza,it Serie A,33-355,1990.0,11.5,5.0,...,50.0,2.0,6.0,2.0,4.0,0,5.0,21.0,0.0,Matches
2795,2796,Mateusz Łęgowski,pl POL,MF,Salernitana,it Serie A,21-103,2003.0,12.3,22.0,...,40.0,15.0,12.0,2.0,10.0,7,29.0,15.0,0.0,Matches

In [7]:
# Current column names
current_columns = [
    'Rk',
    'Player',
    'Nation',
    'Pos',
    'Squad',
    'Comp',
    'Age',
    'Born',
    '90s',
    'Tkl',
    'TklW',
    'Def 3rd',
    'Mid 3rd',
    'Att 3rd',
    'Tkl.1',
    'Att',
    'Tkl%',
    'Lost',
    'Blocks',
    'Sh',
    'Pass',
    'Int',
    'Tkl+Int',
    'Clr',
    'Err',
    'Matches'
]

# New column names
new_columns = [
    'Rk',
    'Player',
    'Nation',
    'Pos',
    'Squad',
    'Comp',
    'Age',
    'Born',
    '90s',
    'Tackles Tkl',
    'Tackles TklW',
    'Tackles Def 3rd',
    'Tackles Mid 3rd',
    'Tackles Att 3rd',
    'Challenges Tkl',
    'Challenges Att',
    'Challenges Tkl%',
    'Challenges Lost',
    'Blocks Blocks',
    'Blocks Sh',
    'Blocks Pass',
    'Int',
    'Tkl+Int',
    'Clr',
    'Err',
    'Matches'
]



ndf.columns = new_columns

In [8]:
ndf.columns.tolist()

['Rk',
 'Player',
 'Nation',
 'Pos',
 'Squad',
 'Comp',
 'Age',
 'Born',
 '90s',
 'Tackles Tkl',
 'Tackles TklW',
 'Tackles Def 3rd',
 'Tackles Mid 3rd',
 'Tackles Att 3rd',
 'Challenges Tkl',
 'Challenges Att',
 'Challenges Tkl%',
 'Challenges Lost',
 'Blocks Blocks',
 'Blocks Sh',
 'Blocks Pass',
 'Int',
 'Tkl+Int',
 'Clr',
 'Err',
 'Matches']

In [9]:
ndf.to_csv('defense_stats_.csv', index = False)

In [10]:
ndf

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Tackles Tkl,...,Challenges Tkl%,Challenges Lost,Blocks Blocks,Blocks Sh,Blocks Pass,Int,Tkl+Int,Clr,Err,Matches
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,24-128,2000.0,13.0,29.0,...,62.5,12.0,9.0,5.0,4.0,6,35.0,25.0,0.0,Matches
1,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,23-202,2000.0,12.6,29.0,...,50.0,15.0,25.0,0.0,25.0,2,31.0,4.0,0.0,Matches
2,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,20-259,2003.0,1.1,2.0,...,100.0,0.0,2.0,0.0,2.0,0,2.0,0.0,0.0,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,18-036,2006.0,0.0,0.0,...,NaN,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,Matches
4,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,36-226,1987.0,28.9,59.0,...,56.8,19.0,46.0,27.0,19.0,37,96.0,101.0,1.0,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2791,2792,Lovro Zvonarek,hr CRO,MF,Bayern Munich,de Bundesliga,19-003,2005.0,0.2,0.0,...,0.0,1.0,1.0,0.0,1.0,0,0.0,1.0,0.0,Matches
2792,2793,Martin Ødegaard,no NOR,MF,Arsenal,eng Premier League,25-146,1998.0,32.4,46.0,...,29.6,38.0,22.0,1.0,21.0,13,59.0,5.0,0.0,Matches
2793,2794,Milan Đurić,ba BIH,FW,Hellas Verona,it Serie A,33-355,1990.0,13.4,1.0,...,0.0,3.0,0.0,0.0,0.0,1,2.0,13.0,0.0,Matches
2794,2795,Milan Đurić,ba BIH,FW,Monza,it Serie A,33-355,1990.0,11.5,5.0,...,50.0,2.0,6.0,2.0,4.0,0,5.0,21.0,0.0,Matches
2795,2796,Mateusz Łęgowski,pl POL,MF,Salernitana,it Serie A,21-103,2003.0,12.3,22.0,...,40.0,15.0,12.0,2.0,10.0,7,29.0,15.0,0.0,Matches